
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/qrconnect?sslmode=disable
      - JWT_SECRET=your_secure_jwt_secret_here
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: unless-stopped
    command: sh -c "cd /app && go mod tidy && go run ."

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qrconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
